---
title: "Alchemab_bulkseq_scseq_comparison"
author: "Khang"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    keep_tex: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
knitr::opts_chunk$set(dev = "png",
                      dpi = 300, out.width = "100%", out.height = "100%",
                      echo = FALSE,
                      cache = TRUE)
```

```{r libs, include=FALSE}
library(immunarch)
library(tidyverse)
library(vegan)
library(pheatmap)
library(ggplotify)
library(cowplot)
library(reshape2)
library(seqinr)
library(GGally)
library(RColorBrewer)
library(magick)
```

```{r eval=FALSE, include=FALSE}
# Load the data
data_all_bulk <- readRDS("../bulkseq_data/data_bulk_isotypes")
data_all_bulk$meta <- data_all_bulk$meta[,-7]
data_all_sc <- readRDS("../sc_data/data_sc_isotypes")


data_all_both <- list(data = c(data_all_bulk$data, data_all_sc$data),
                      meta = rbind(data_all_bulk$meta, data_all_sc$meta))

# Save the data
saveRDS(data_all_both, "./data_all_both")
```

```{r}
# Load the data
data_all_both <- readRDS("./data_all_both")
```

# Clonal proportions

```{r Clonal_proportion, echo=FALSE, fig.height=6, fig.width=10, message=FALSE, warning=FALSE}
# Relative abundance
imm_homeo <- repClonality(data_all_both$data, .method = "homeo")
vis(imm_homeo)
vis(imm_homeo, .meta = data_all_both$meta, .by = "Method")
```

# VH gene usage

```{r VH-gene_usage_isotype, fig.height=6, fig.width=16, message=FALSE, warning=FALSE}
#V gene usage heavy chain
gene_use_hv_isotypes <- geneUsage(data_all_both$data[-str_which(names(data_all_both$data),"IgE|IgK|IgL")], .gene= c("hs.ighv"), .ambig = "maj", .norm = TRUE, .quant = "count")

gene_use_hv_isotypes_2 <- gene_use_hv_isotypes
gene_use_hv_isotypes_2[is.na(gene_use_hv_isotypes_2)] <- 0

#Filter for rows with gene names beginning with IGHV
gene_use_hv_isotypes <- gene_use_hv_isotypes[grep("^IGHV",gene_use_hv_isotypes$Names),]

vis(gene_use_hv_isotypes, .title = "VH-Gene usage by isotype", .meta = data_all_both$meta, .by = c("Isotype", "Method"), .add.layer = scale_y_continuous(breaks = seq(0.0, 0.25, by = 0.05), limits = c(0.00,0.15)))
```

# VH gene usage correlation
# Todo: make 3 scatterplot representing high, medium, and low overlap.

```{r VH-gene_usage_correlation_isotype, fig.height=16, fig.width=16}
vh_cor_pearson_isotype <- geneUsageAnalysis(gene_use_hv_isotypes, .method = "cor", .cor = "pearson", .verbose = F)
vh_cor_pearson_isotype_2 <- geneUsageAnalysis(gene_use_hv_isotypes_2, .method = "cor", .cor = "pearson", .verbose = F)

vh_jsd_isotype <- geneUsageAnalysis(gene_use_hv_isotypes, .method = "js", .verbose = F)
vis(vh_jsd_isotype)

vh_cor_spearman_isotype <- geneUsageAnalysis(gene_use_hv_isotypes, .method = "cor", .cor = "spearman", .verbose = F)

# Create a separate df with rownames matching the sample names
annotation_df_isotype <- data.frame(Isotype = data_all_both$meta$Isotype,
                                    Donor_Id = data_all_both$meta$Donor_Id,
                                    Method = data_all_both$meta$Method)
rownames(annotation_df_isotype) <- data_all_both$meta$Sample

# Specify which color goes to which sample and isotype for the annotation
annotation_colors_isotype <- list(Isotype = brewer.pal(4, "Set1"),
                                  Donor_Id = brewer.pal(10,"Set3"),
                                  Method = c("#404040","#bababa"))
names(annotation_colors_isotype$Isotype) <- c("IgA", "IgD", "IgG", "IgM")
names(annotation_colors_isotype$Donor_Id) <- unique(data_all_both$meta$Donor_Id)
names(annotation_colors_isotype$Method) <- unique(data_all_both$meta$Method)

# Calculate the distance based on correlation values
dist_pearson <- as.dist(1-cor(gene_use_hv_isotypes[,-1], method = "pearson", use = "na.or.complete"))
hc_pearson <- hclust(dist_pearson, method = "ward.D2")

# set up panel of 2x2 plots:
#par(mfrow=c(2,2))

# plots for 2, 3, and 4 clusters:
#plot(silhouette(cutree(hc_pearson,3),dist_pearson))
#plot(silhouette(cutree(hc_pearson,4),dist_pearson))
#plot(silhouette(cutree(hc_pearson,5),dist_pearson))
#plot(silhouette(cutree(hc_pearson,6),dist_pearson))

# Draw the cor plot (remember to make silhouette plot to justify cluster number)
p_cor_pearson_isotype <- as.ggplot(pheatmap(vh_cor_pearson_isotype, cluster_rows = T, cluster_cols = T, na_col = "gray80", silent = T, clustering_method = "ward.D2",
                     clustering_distance_rows = dist_pearson, clustering_distance_cols = dist_pearson,
                     border_color = "white", angle_col = 90,
                     main = "VH-gene usage by isotype Pearson correlation",
                     display_numbers = F, number_color = "black", fontsize_number = 10,
                     annotation = annotation_df_isotype, annotation_row = annotation_df_isotype,
                     annotation_colors = annotation_colors_isotype,
                     cutree_rows = 4 , cutree_cols = 4,
                     breaks = seq(round(min(vh_cor_pearson_isotype, na.rm = T),1), 1.0, by = 0.05),
                     legend_breaks = seq(round(min(vh_cor_pearson_isotype, na.rm = T),1), 1.0, by = 0.05),
                     legend_labels = c(seq(round(min(vh_cor_pearson_isotype, na.rm = T),1), 0.95, by = 0.05), "Cor"), # The breaks vector needs to be ONE element longer than the color vector
                     color = colorRampPalette(c("#ffffb2", "#e31a1c"))(length(seq(round(min(vh_cor_pearson_isotype, na.rm = T),1), 1.0, by = 0.05))),
                     ))

# Determine the optimal number of cluster
dist_spearman <- as.dist(1-cor(gene_use_hv_isotypes[,-1], method = "spearman", use = "na.or.complete"))
hc_spearman <- hclust(dist_spearman, method = "ward.D2")

p_cor_spearman_isotype <- as.ggplot(pheatmap(vh_cor_spearman_isotype, cluster_rows = T, cluster_cols = T, na_col = "gray80", silent = T, clustering_method = "ward.D2", clustering_distance_rows = dist_spearman, clustering_distance_cols = dist_spearman,
                     border_color = "white", main = "VH-gene usage by isotype Spearman correlation",
                     display_numbers = F, number_color = "black", fontsize_number = 10,
                     angle_col = 90,
                     annotation = annotation_df_isotype, annotation_row = annotation_df_isotype,
                     annotation_colors = annotation_colors_isotype,
                     cutree_rows = 4, cutree_cols = 4,
                     breaks = seq(round(min(vh_cor_spearman_isotype, na.rm = T),1), 1.0, by = 0.05),
                     legend_breaks = seq(round(min(vh_cor_spearman_isotype, na.rm = T),1), 1.0, by = 0.05),
                     legend_labels = c(seq(round(min(vh_cor_spearman_isotype, na.rm = T),1), 0.95, by = 0.05), "Cor"), # The breaks vector needs to be ONE element longer than the color vector
                     color = colorRampPalette(c("#ffffb2", "#e31a1c"))(length(seq(round(min(vh_cor_spearman_isotype, na.rm = T),1), 1.0, by = 0.05)))
                     ))

p_cor_pearson_isotype
p_cor_spearman_isotype

ggsave("./bulk_sc_comparison_figures/VH-gene_usage_correlation_isotypes_pearson.png", p_cor_pearson_isotype, width = 18, height = 18, dpi = "retina")

ggsave("./bulk_sc_comparison_figures/VH-gene_usage_correlation_isotypes_spearman.png", p_cor_spearman_isotype, width = 18, height = 18, dpi = "retina")
```

```{r}
# Selet a few correlation comparisons and check them using scatterplot
ggplot(gene_use_hv_isotypes, aes(x = `J2NM7945-A_IgD_bulk`, y = `J2NM7945-A_IgD_sc`)) +
  geom_point() +
  lims(x = c(0, 0.15), y = c(0, 0.15)) +
  geom_text(x = 0.13, y = 0.13, label = paste0("Pearson's r ", round(cor(gene_use_hv_isotypes_2$`J2NM7945-A_IgD_bulk`, gene_use_hv_isotypes$`J2NM7945-A_IgD_sc`, method = "pearson", use = "complete.obs"),2))) +
  theme_classic() +
  theme(panel.border = element_rect(fill=NA)) + # Add a border to the plot
  geom_smooth(method = lm, se = FALSE) # Add regression line

ggplot(gene_use_hv_isotypes, aes(x = `J2NM7891-A_IgA_bulk`, y = `J2NM7891-A_IgG_bulk`)) +
  geom_point() +
  lims(x = c(0, 0.15), y = c(0, 0.15)) +
  geom_text(x = 0.13, y = 0.13, label = paste0("Pearson's r ", round(cor(gene_use_hv_isotypes_2$`J2NM7891-A_IgA_bulk`, gene_use_hv_isotypes$`J2NM7891-A_IgG_bulk`, method = "pearson", use = "complete.obs"),2))) +
  theme_classic() +
  theme(panel.border = element_rect(fill=NA)) + # Add a border to the plot
  geom_smooth(method = lm, se = FALSE) # Add regression line
```

```{r}
# Visualize the pearson correlation of VH gene usage using box plots
# Convert matrix to long format
vh_cor_pearson_isotype_long <- pivot_longer(as_tibble(vh_cor_pearson_isotype), cols = everything(), names_to = "Target", values_to = "Cor")
vh_cor_pearson_isotype_long$Sample <- rep(rownames(vh_cor_pearson_isotype), each = ncol(vh_cor_pearson_isotype))
vh_cor_pearson_isotype_long <- merge(vh_cor_pearson_isotype_long, data_all_both$meta)
vh_cor_pearson_isotype_long$Donor_Id_Target <- str_split(vh_cor_pearson_isotype_long$Target, "_", simplify = T)[,1]
vh_cor_pearson_isotype_long$Isotype_Target <- str_split(vh_cor_pearson_isotype_long$Target, "_", simplify = T)[,2]

vh_cor_pearson_isotype_median <- vh_cor_pearson_isotype_long %>% group_by(Donor_Id, Method, Isotype) %>% summarise(Median = median(Cor, na.rm = T))
#ggplot(data = vh_cor_pearson_isotype_long) +
  #geom_boxplot(aes(x = Donor_Id, y = Cor, fill = Donor_Id), color = "black") +
  #scale_fill_brewer(type = "qual", palette = "Set3") +
  #theme_half_open() +
  #theme(axis.text.x = element_text(angle = 90)) + #Rotate text 90 degrees
  #facet_wrap(vars(Isotype))

p_cor_pearson_isotype_box <-  ggplot(data = vh_cor_pearson_isotype_long) +
  geom_violin(aes(x = Isotype, y = Cor, fill = Isotype), outlier.shape = NA) +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  geom_boxplot(aes(x = Isotype, y = Cor, fill = Isotype), width = 0.2, color= "black") +
  #scale_color_brewer(type = "qual", palette = "Set3") +
  theme_half_open() +
  theme(axis.text.x = element_text(angle = 0)) + #Rotate text 90 degrees
  labs(title = "VH-gene usage Pearson correlation by isotype") +
  facet_wrap(vars(Method))

p_cor_pearson_donor_box <-  ggplot(data = vh_cor_pearson_isotype_long) +
  geom_violin(aes(x = Isotype, y = Cor, fill = Isotype), alpha = 0.8, outlier.shape = NA) +
  #scale_fill_brewer(type = "qual", palette = "Set3") +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  geom_boxplot(aes(x = Isotype, y = Cor, fill = Isotype), width = 0.2, color= "black") +
  geom_text(data = vh_cor_pearson_isotype_median, aes(x = Isotype, y = 1.0, label = round(Median,2)), vjust = -0.05) +
  ylim(c(0.39,1.1)) +
  #scale_color_brewer(type = "qual", palette = "Set3") +
  theme_half_open() +
  theme(axis.text.x = element_text(angle = 0)) + #Rotate text 90 degrees
  labs(title = "VH-gene usage Pearson correlation by donor") +
  facet_grid(rows = vars(Donor_Id), cols = vars(Method))
```

```{r fig.height=5, fig.width=8}
p_cor_pearson_isotype_box
ggsave("./bulk_sc_comparison_figures/VH-gene_usage_correlation_pearson_isotype_box.png", p_cor_pearson_isotype_box, width = 8, height = 6, dpi = "retina")
```

```{r fig.height=10, fig.width=5}
p_cor_pearson_donor_box
ggsave("./bulk_sc_comparison_figures/VH-gene_usage_correlation_pearson_donor_box.png", p_cor_pearson_donor_box, width = 8, height = 12, dpi = "retina")
```


\newpage

# Repertoire overlap (shared CDR3 sequence)
# Todo: make 3 scatterplot representing high, medium, and low overlap (point arrows out from each tile). Implement normalized overlap score method

```{r}
cdr3_overlap_jaccard_isotype <- (repOverlap(data_all_both$data[-str_which(names(data_all_both$data),"IgE|IgK|IgL")], .method = "jaccard",.col ="aa", .verbose = F))
#cdr3_overlap_morisita <- (repOverlap(data_all_both$data[-str_which(names(data_all_both$data),"IgE|IgK|IgL")], .method = "morisita", .col ="aa", .verbose = F))
#saveRDS(cdr3_overlap_morisita, "./cdr3_overlap_morisita")

cdr3_overlap_morisita <- readRDS("./cdr3_overlap_morisita")

p_cdr3_overlap_jaccard_isotype <- as.ggplot(
  pheatmap(cdr3_overlap_jaccard_isotype, cluster_rows = T, cluster_cols = T, clustering_method = "complete",
           #cutree_rows = 3, cutree_cols = 3,
           border_color = "white", #na_col =  "gray3",
           main = "Shared CDR3 sequences Jaccard overlap by isotype",
           angle_col = 90, display_numbers = F, number_color = "black",
           number_format = "%.2f", silent = T, fontsize_number = 10,
           annotation = annotation_df_isotype, annotation_row = annotation_df_isotype,
           annotation_colors = annotation_colors_isotype,
           color = colorRampPalette(c("#ffffb2", "#e31a1c"))(25)
           ))

p_cdr3_overlap_morisita_isotype <- as.ggplot(
  pheatmap(cdr3_overlap_morisita, cluster_rows = T, cluster_cols = T, clustering_method = "complete",
           #cutree_rows = 3, cutree_cols = 3,
           border_color = "white", #na_col =  "gray3",
           main = "Shared CDR3 sequences Morisita-Horn overlap by isotype",
           angle_col = 90, display_numbers = F, number_color = "black",
           number_format = "%.2f", silent = T, fontsize_number = 10,
           annotation = annotation_df_isotype, annotation_row = annotation_df_isotype,
           annotation_colors = annotation_colors_isotype,
           color = colorRampPalette(c("#ffffb2", "#e31a1c"))(25)
           ))
```

```{r Repertoire_overlap_isotype_jaccard, fig.height=16, fig.width=16}
p_cdr3_overlap_jaccard_isotype
ggsave("./bulk_sc_comparison_figures/Repertoire_overlap_isotype_jaccard.png", p_cdr3_overlap_jaccard_isotype, width = 18, height = 18, dpi = "retina")
```
\newpage
```{r Repertoire_overlap_isotype_morisita, fig.height=16, fig.width=16}
p_cdr3_overlap_morisita_isotype
ggsave("./bulk_sc_comparison_figures/Repertoire_overlap_isotype_morisita.png", p_cdr3_overlap_morisita_isotype, width = 18, height = 18, dpi = "retina")
```